from typing import Protocol
from app.domain.entities.recording import Recording, RecordingStatus


class RecordingRepository(Protocol):
    def save(self, recording: Recording) -> Recording: ...
    def get(self, recording_id: str) -> Recording | None: ...
    def list(self, status: RecordingStatus | None = None) -> list[Recording]: ...
    def review(self, recording_id: str, status: RecordingStatus, reason: str | None) -> Recording | None: ...
